# Reproduce bug

- Add a dsn.txt with your DSN (or just add it to the `settings.py`)
- Run `./manage.py bug`
